function filenames = getFileNames(dictors,... 
utterances, voice, variance, data, noise, noiseValue)
filenames = {};
for i=1:length(dictors)
    dictor = int2str(dictors(i));
    for j=1:length(utterances)
        utterance = int2str(utterances(j));
        name = strcat(  voice,...
            dictor,...
            variance,...
            utterance,...
            data,...
            noise,...
            noiseValue);
        filenames{end+1} = name;
    end
end